---
- name: add webdata file
  hosts: appservers
  tasks:
  - name: create file
    file:
      path: /tmp/web.txt
      state: touch
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0777
    become: yes